name: 'Deploy'
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  deploy: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get or Create Release at current tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Lets us upload our own artifact from previous step
          artifactErrorsFailBuild: true
          artifacts: './index'
          token: ${{ secrets.GITHUB_TOKEN }}
